name: Test

on:
  watch:
    types: 
      - started

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login
         
    steps:
      #- name: Checkout shm_size branch
      #  uses: actions/checkout@v2
      #  with:
      #    ref: shm_size
            
      #- name: Pull the Hassio Builder
      #  run: sudo docker pull homeassistant/amd64-builder
        
      #- name: check help file
      #  run: docker run --rm --privileged homeassistant/amd64-builder --help
        
      #- name: Docker login
      #  run: sudo docker login -u ${{ secrets.docker_hub_username }} -p ${{ secrets.docker_hub_password }}
        
      - name: Test 1
        run: echo $(pwd)
        
      - name: Test 2
        run: echo $(PWD)
        
      - name: Test 3
        run: echo ${PWD}      
         
      - name: Build
        run: sudo docker run --rm --privileged \
             -v ~/.docker:/root/.docker \
             -v ${PWD}:/data:ro \
             #-v /run/docker.sock:/run/docker.sock:rw \
             homeassistant/amd64-builder --amd64 --no-latest \
             -t /data \
             # --generic shm_size \
             # -d mories -i supervisor
