name: Test

on:
  watch:
    types: 
      - started

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login
    
        
    steps:
      - name: Checkout shm_size branch
        uses: actions/checkout@v2
        with:
          ref: shm_size
            
      - name: Pull the Hassio Builder
        run: docker pull homeassistant/amd64-builder
        
      - name: check help file
        run: docker run --rm --privileged homeassistant/amd64-builder --help
        
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
